import { httpsCallable } from 'firebase/functions';
import { functions } from './firebase';

export type ColorSuggestion = {
  /** Hex of the suggestion, e.g. "#ff4a1c". May be a palette entry or a
   *  custom hex generated by the model. */
  color: string;
  /** "palette" = picked from listed palette; "custom" = AI-generated hex
   *  for a color the palette doesn't cover (e.g. greys). */
  source: 'palette' | 'custom';
  rationale: string;
};

const callable = httpsCallable<
  { storagePath: string; excludeColors: string[] },
  { suggestions: ColorSuggestion[] }
>(functions, 'suggestTeamColor', { timeout: 60_000 });

export async function suggestTeamColor(args: {
  storagePath: string;
  excludeColors: string[];
}): Promise<ColorSuggestion[]> {
  const res = await callable(args);
  return res.data.suggestions;
}
